[package]
name = "sim-core"
version.workspace = true
edition.workspace = true

[dependencies]
sim-math = { path = "../sim-math" }
sim-components = { path = "../sim-components" }
sim-physics = { path = "../sim-physics" }
sim-rules = { path = "../sim-rules" }
sim-ai-player = { path = "../sim-ai-player" }
sim-ai-core = { path = "../sim-ai-core" }
bevy_ecs.workspace = true
serde.workspace = true
smallvec.workspace = true
rand.workspace = true

[lints]
workspace = true