[package]
name = "sim-ai-player"
version.workspace = true
edition.workspace = true

[dependencies]
sim-math = { path = "../sim-math" }
sim-components = { path = "../sim-components" }
sim-ai-core = { path = "../sim-ai-core" }
sim-physics = { path = "../sim-physics" }
bevy_ecs.workspace = true
smallvec.workspace = true
rand.workspace = true

[lints]
workspace = true