[package]
name = "sim-ai-player"
version.workspace = true
edition.workspace = true

[dependencies]
sim-math = { path = "../sim-math" }
sim-components = { path = "../sim-components" }
sim-ai-core = { path = "../sim-ai-core" }
sim-physics = { path = "../sim-physics" }
bevy_ecs.workspace = true
smallvec.workspace = true
tracing.workspace = true
sim-telemetry = { path = "../sim-telemetry" }

[lints]
workspace = true

[dev-dependencies]
serde_json = "1"