[package]
name = "sim-rules"
version.workspace = true
edition.workspace = true

[dependencies]
sim-math = { path = "../sim-math" }
sim-components = { path = "../sim-components" }
sim-telemetry = { path = "../sim-telemetry" }
bevy_ecs.workspace = true
tracing.workspace = true

[lints]
workspace = true