[package]
name = "sim-server"
version.workspace = true
edition.workspace = true

[dependencies]
sim-math = { path = "../sim-math" }
sim-components = { path = "../sim-components" }
sim-core = { path = "../sim-core" }
sim-replay = { path = "../sim-replay" }
bevy_ecs.workspace = true

[[bin]]
name = "football-sim"
path = "src/main.rs"

[lints]
workspace = true